// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: entities.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AElf.Contracts.Resource {

  /// <summary>Holder for reflection information generated from entities.proto</summary>
  public static partial class EntitiesReflection {

    #region Descriptor
    /// <summary>File descriptor for entities.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EntitiesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5lbnRpdGllcy5wcm90bxoMY29tbW9uLnByb3RvGg5yZXNvdXJjZS5wcm90",
            "byJ+CglDb252ZXJ0ZXISEgoKUmVzQmFsYW5jZRgBIAEoBBISCgpFbGZCYWxh",
            "bmNlGAIgASgEEhEKCVJlc1dlaWdodBgDIAEoBBIRCglFbGZXZWlnaHQYBCAB",
            "KAQSIwoMUmVzb3VyY2VUeXBlGAUgASgOMg0uUmVzb3VyY2VUeXBlIkkKD1Vz",
            "ZXJSZXNvdXJjZUtleRIZCgdBZGRyZXNzGAEgASgLMgguQWRkcmVzcxIbCgRU",
            "eXBlGAIgASgOMg0uUmVzb3VyY2VUeXBlQhqqAhdBRWxmLkNvbnRyYWN0cy5S",
            "ZXNvdXJjZWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::AElf.Common.CommonReflection.Descriptor, global::AElf.Kernel.ResourceReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AElf.Contracts.Resource.Converter), global::AElf.Contracts.Resource.Converter.Parser, new[]{ "ResBalance", "ElfBalance", "ResWeight", "ElfWeight", "ResourceType" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AElf.Contracts.Resource.UserResourceKey), global::AElf.Contracts.Resource.UserResourceKey.Parser, new[]{ "Address", "Type" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Converter : pb::IMessage<Converter> {
    private static readonly pb::MessageParser<Converter> _parser = new pb::MessageParser<Converter>(() => new Converter());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Converter> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AElf.Contracts.Resource.EntitiesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Converter() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Converter(Converter other) : this() {
      resBalance_ = other.resBalance_;
      elfBalance_ = other.elfBalance_;
      resWeight_ = other.resWeight_;
      elfWeight_ = other.elfWeight_;
      resourceType_ = other.resourceType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Converter Clone() {
      return new Converter(this);
    }

    /// <summary>Field number for the "ResBalance" field.</summary>
    public const int ResBalanceFieldNumber = 1;
    private ulong resBalance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong ResBalance {
      get { return resBalance_; }
      set {
        resBalance_ = value;
      }
    }

    /// <summary>Field number for the "ElfBalance" field.</summary>
    public const int ElfBalanceFieldNumber = 2;
    private ulong elfBalance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong ElfBalance {
      get { return elfBalance_; }
      set {
        elfBalance_ = value;
      }
    }

    /// <summary>Field number for the "ResWeight" field.</summary>
    public const int ResWeightFieldNumber = 3;
    private ulong resWeight_;
    /// <summary>
    /// Weight based on MAX of 1,000,000
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong ResWeight {
      get { return resWeight_; }
      set {
        resWeight_ = value;
      }
    }

    /// <summary>Field number for the "ElfWeight" field.</summary>
    public const int ElfWeightFieldNumber = 4;
    private ulong elfWeight_;
    /// <summary>
    /// Weight based on MAX of 1,000,000
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong ElfWeight {
      get { return elfWeight_; }
      set {
        elfWeight_ = value;
      }
    }

    /// <summary>Field number for the "ResourceType" field.</summary>
    public const int ResourceTypeFieldNumber = 5;
    private global::AElf.Kernel.ResourceType resourceType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::AElf.Kernel.ResourceType ResourceType {
      get { return resourceType_; }
      set {
        resourceType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Converter);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Converter other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResBalance != other.ResBalance) return false;
      if (ElfBalance != other.ElfBalance) return false;
      if (ResWeight != other.ResWeight) return false;
      if (ElfWeight != other.ElfWeight) return false;
      if (ResourceType != other.ResourceType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ResBalance != 0UL) hash ^= ResBalance.GetHashCode();
      if (ElfBalance != 0UL) hash ^= ElfBalance.GetHashCode();
      if (ResWeight != 0UL) hash ^= ResWeight.GetHashCode();
      if (ElfWeight != 0UL) hash ^= ElfWeight.GetHashCode();
      if (ResourceType != 0) hash ^= ResourceType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ResBalance != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(ResBalance);
      }
      if (ElfBalance != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(ElfBalance);
      }
      if (ResWeight != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(ResWeight);
      }
      if (ElfWeight != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(ElfWeight);
      }
      if (ResourceType != 0) {
        output.WriteRawTag(40);
        output.WriteEnum((int) ResourceType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ResBalance != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ResBalance);
      }
      if (ElfBalance != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ElfBalance);
      }
      if (ResWeight != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ResWeight);
      }
      if (ElfWeight != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ElfWeight);
      }
      if (ResourceType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ResourceType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Converter other) {
      if (other == null) {
        return;
      }
      if (other.ResBalance != 0UL) {
        ResBalance = other.ResBalance;
      }
      if (other.ElfBalance != 0UL) {
        ElfBalance = other.ElfBalance;
      }
      if (other.ResWeight != 0UL) {
        ResWeight = other.ResWeight;
      }
      if (other.ElfWeight != 0UL) {
        ElfWeight = other.ElfWeight;
      }
      if (other.ResourceType != 0) {
        ResourceType = other.ResourceType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ResBalance = input.ReadUInt64();
            break;
          }
          case 16: {
            ElfBalance = input.ReadUInt64();
            break;
          }
          case 24: {
            ResWeight = input.ReadUInt64();
            break;
          }
          case 32: {
            ElfWeight = input.ReadUInt64();
            break;
          }
          case 40: {
            resourceType_ = (global::AElf.Kernel.ResourceType) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  public sealed partial class UserResourceKey : pb::IMessage<UserResourceKey> {
    private static readonly pb::MessageParser<UserResourceKey> _parser = new pb::MessageParser<UserResourceKey>(() => new UserResourceKey());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UserResourceKey> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AElf.Contracts.Resource.EntitiesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserResourceKey() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserResourceKey(UserResourceKey other) : this() {
      address_ = other.address_ != null ? other.address_.Clone() : null;
      type_ = other.type_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserResourceKey Clone() {
      return new UserResourceKey(this);
    }

    /// <summary>Field number for the "Address" field.</summary>
    public const int AddressFieldNumber = 1;
    private global::AElf.Common.Address address_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::AElf.Common.Address Address {
      get { return address_; }
      set {
        address_ = value;
      }
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 2;
    private global::AElf.Kernel.ResourceType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::AElf.Kernel.ResourceType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UserResourceKey);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UserResourceKey other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Address, other.Address)) return false;
      if (Type != other.Type) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (address_ != null) hash ^= Address.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (address_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Address);
      }
      if (Type != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (address_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Address);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UserResourceKey other) {
      if (other == null) {
        return;
      }
      if (other.address_ != null) {
        if (address_ == null) {
          address_ = new global::AElf.Common.Address();
        }
        Address.MergeFrom(other.Address);
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (address_ == null) {
              address_ = new global::AElf.Common.Address();
            }
            input.ReadMessage(address_);
            break;
          }
          case 16: {
            type_ = (global::AElf.Kernel.ResourceType) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
