// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: parent-chain-block-info.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AElf.Contracts.SideChain {

  /// <summary>Holder for reflection information generated from parent-chain-block-info.proto</summary>
  public static partial class ParentChainBlockInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for parent-chain-block-info.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ParentChainBlockInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1wYXJlbnQtY2hhaW4tYmxvY2staW5mby5wcm90bxoMY29tbW9uLnByb3Rv",
            "IpYBChhQYXJlbnRDaGFpbkJsb2NrUm9vdEluZm8SDgoGSGVpZ2h0GAEgASgE",
            "EigKGVNpZGVDaGFpbkJsb2NrSGVhZGVyc1Jvb3QYAiABKAsyBS5IYXNoEigK",
            "GVNpZGVDaGFpblRyYW5zYWN0aW9uc1Jvb3QYAyABKAsyBS5IYXNoEhYKB0No",
            "YWluSWQYBCABKAsyBS5IYXNoQhuqAhhBRWxmLkNvbnRyYWN0cy5TaWRlQ2hh",
            "aW5iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::AElf.Common.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AElf.Contracts.SideChain.ParentChainBlockRootInfo), global::AElf.Contracts.SideChain.ParentChainBlockRootInfo.Parser, new[]{ "Height", "SideChainBlockHeadersRoot", "SideChainTransactionsRoot", "ChainId" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ParentChainBlockRootInfo : pb::IMessage<ParentChainBlockRootInfo> {
    private static readonly pb::MessageParser<ParentChainBlockRootInfo> _parser = new pb::MessageParser<ParentChainBlockRootInfo>(() => new ParentChainBlockRootInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ParentChainBlockRootInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AElf.Contracts.SideChain.ParentChainBlockInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ParentChainBlockRootInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ParentChainBlockRootInfo(ParentChainBlockRootInfo other) : this() {
      height_ = other.height_;
      sideChainBlockHeadersRoot_ = other.sideChainBlockHeadersRoot_ != null ? other.sideChainBlockHeadersRoot_.Clone() : null;
      sideChainTransactionsRoot_ = other.sideChainTransactionsRoot_ != null ? other.sideChainTransactionsRoot_.Clone() : null;
      chainId_ = other.chainId_ != null ? other.chainId_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ParentChainBlockRootInfo Clone() {
      return new ParentChainBlockRootInfo(this);
    }

    /// <summary>Field number for the "Height" field.</summary>
    public const int HeightFieldNumber = 1;
    private ulong height_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Height {
      get { return height_; }
      set {
        height_ = value;
      }
    }

    /// <summary>Field number for the "SideChainBlockHeadersRoot" field.</summary>
    public const int SideChainBlockHeadersRootFieldNumber = 2;
    private global::AElf.Common.Hash sideChainBlockHeadersRoot_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::AElf.Common.Hash SideChainBlockHeadersRoot {
      get { return sideChainBlockHeadersRoot_; }
      set {
        sideChainBlockHeadersRoot_ = value;
      }
    }

    /// <summary>Field number for the "SideChainTransactionsRoot" field.</summary>
    public const int SideChainTransactionsRootFieldNumber = 3;
    private global::AElf.Common.Hash sideChainTransactionsRoot_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::AElf.Common.Hash SideChainTransactionsRoot {
      get { return sideChainTransactionsRoot_; }
      set {
        sideChainTransactionsRoot_ = value;
      }
    }

    /// <summary>Field number for the "ChainId" field.</summary>
    public const int ChainIdFieldNumber = 4;
    private global::AElf.Common.Hash chainId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::AElf.Common.Hash ChainId {
      get { return chainId_; }
      set {
        chainId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ParentChainBlockRootInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ParentChainBlockRootInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Height != other.Height) return false;
      if (!object.Equals(SideChainBlockHeadersRoot, other.SideChainBlockHeadersRoot)) return false;
      if (!object.Equals(SideChainTransactionsRoot, other.SideChainTransactionsRoot)) return false;
      if (!object.Equals(ChainId, other.ChainId)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Height != 0UL) hash ^= Height.GetHashCode();
      if (sideChainBlockHeadersRoot_ != null) hash ^= SideChainBlockHeadersRoot.GetHashCode();
      if (sideChainTransactionsRoot_ != null) hash ^= SideChainTransactionsRoot.GetHashCode();
      if (chainId_ != null) hash ^= ChainId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Height != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Height);
      }
      if (sideChainBlockHeadersRoot_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(SideChainBlockHeadersRoot);
      }
      if (sideChainTransactionsRoot_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(SideChainTransactionsRoot);
      }
      if (chainId_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ChainId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Height != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Height);
      }
      if (sideChainBlockHeadersRoot_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SideChainBlockHeadersRoot);
      }
      if (sideChainTransactionsRoot_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SideChainTransactionsRoot);
      }
      if (chainId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChainId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ParentChainBlockRootInfo other) {
      if (other == null) {
        return;
      }
      if (other.Height != 0UL) {
        Height = other.Height;
      }
      if (other.sideChainBlockHeadersRoot_ != null) {
        if (sideChainBlockHeadersRoot_ == null) {
          sideChainBlockHeadersRoot_ = new global::AElf.Common.Hash();
        }
        SideChainBlockHeadersRoot.MergeFrom(other.SideChainBlockHeadersRoot);
      }
      if (other.sideChainTransactionsRoot_ != null) {
        if (sideChainTransactionsRoot_ == null) {
          sideChainTransactionsRoot_ = new global::AElf.Common.Hash();
        }
        SideChainTransactionsRoot.MergeFrom(other.SideChainTransactionsRoot);
      }
      if (other.chainId_ != null) {
        if (chainId_ == null) {
          chainId_ = new global::AElf.Common.Hash();
        }
        ChainId.MergeFrom(other.ChainId);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Height = input.ReadUInt64();
            break;
          }
          case 18: {
            if (sideChainBlockHeadersRoot_ == null) {
              sideChainBlockHeadersRoot_ = new global::AElf.Common.Hash();
            }
            input.ReadMessage(sideChainBlockHeadersRoot_);
            break;
          }
          case 26: {
            if (sideChainTransactionsRoot_ == null) {
              sideChainTransactionsRoot_ = new global::AElf.Common.Hash();
            }
            input.ReadMessage(sideChainTransactionsRoot_);
            break;
          }
          case 34: {
            if (chainId_ == null) {
              chainId_ = new global::AElf.Common.Hash();
            }
            input.ReadMessage(chainId_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
